# Generated by Django 2.1 on 2020-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile_stu_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserecord',
            name='homework_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
